<?php
/**
 * @var \Oleksandrk\RegularCustomer\Block\Product\View\DiscountRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
/** @var \Magento\Catalog\Model\Product $product */

$product = $block->getData('product');

// Show form in modal window by default
if ($block->hasData('is_modal')) {
    $isModal = (bool) $block->getData('is_modal');
} else {
    $isModal = 'false';
}
?>

<div class="oleksandrk-personal-regular-discount-form">
    <form class="form oleksandrk-regular-discount-form"
          action="/errors/404.php"
          onsubmit="return false;"
          method="post"
          data-mage-init='{"Oleksandrk_RegularDiscount_Form":{
              "action": "<?= $escaper->escapeHtmlAttr($block->getUrl('regular_customer/request/request/')) ?>",
              "isModal": "<?= $escaper->escapeHtmlAttr($isModal) ?>"
          }}'
    >
        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $escaper->escapeHtml(__('Name')) ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $escaper->escapeHtmlAttr(__('Name')) ?>"
                           class="input-text"
                           type="text"
                           data-validate="{required:true}"
                           required
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"
                           required
                    />
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden"
                       name="product_id"
                       value="<?= $escaper->escapeHtmlAttr(isset($product) ?
                           (int) $product->getId() : null) ?>"
                />
                <input type="hidden"
                       name="productName"
                       value="<?= $escaper->escapeHtmlAttr(isset($product) ?
                           (string) $product->getName() : "General") ?>"
                />
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Send Request')) ?>"
                        class="action submit primary"

                >
                    <span><?= $escaper->escapeHtml(__('Send Request')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
